### PR TITLE
Update link to crisis of confidence letter in "2013-03-25-the-ascent-of-technocracy.txt"

### PR DESCRIPTION
**Pull request by SarangShah87**
Taking an opportunity to familiarize myself with the GitHub UI (which seems intuitive enough for even a non-technical user)

### CODE REVIEW

**Comment by savelbr** [comment]
This broken link seems to suggest I changed the permalinks for the letters from the editor, probably for reasons particular to a previous iteration of the Distilled site. So maybe we should try to restore the original permalinks instead of patching them like this?

**Comment by SarangShah87** [comment]
> This broken link seems to suggest I changed the permalinks for the letters from the editor, probably for reasons particular to a previous iteration of the Distilled site.

Ah, gotcha. Yeah, I was just going to go through each article and fix things up manually, but if you think this is a programmatic issue, feel free to fix it up yourself.

**Comment by savelbr** [comment]
Okay, I added a fix for this to this PR: https://github.com/distilledpm/archives/pull/2. Maybe you could have a look at it and see if you can merge it already. (I think I sent you an invite to the distilledpm organisation, but if you didn't get it I can resend.)

**Comment by SarangShah87** [comment]
Ok cool, just joined the org.

**Pull request closed without merging**
